# Generated by Django 5.0 on 2023-12-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='time_spent',
            new_name='hours_spent',
        ),
        migrations.AddField(
            model_name='activity',
            name='minutes_spent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
