# Generated by Django 5.0 on 2023-12-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_time_spent_activity_hours_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='hours_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='minutes_spent',
            field=models.IntegerField(default=0),
        ),
    ]
